name: fluttercodelabs
description: Flutter Codelabs app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # List of english words
  english_words: ^3.1.5
  # Provider
  provider: ^4.3.2+1
  #GitHub
  github: ^7.0.1
  intl: ^0.16.1
  flutter_markdown: ^0.4.4
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true